version: "3.1"

services:
  scraper:
    build:
      context: .
    volumes: 
      - ./twitter4j.properties:/app/twitter4j.properties
    ports:
      - 4568:8080
    links:
      - twitterscraper-db

  twitterscraper-db:
    image: mongo:latest
    volumes:
      - DB:/data/db
    restart: always
    environment:
      spring.data.mongodb.host: mongodb

volumes:
  DB:

networks:
  default:
    external:
      name: twitternet
